[package]
name = "sx1276"
version = "0.1.0"
authors = ["Nathan Corbyn <me@nathancorbyn.com>"]
edition = "2018"

[dependencies]
bit_field = "0.9.0"
crossbeam = "0.7.1"

[dependencies.embedded-hal]
version = "0.2.2"
features = ["unproven"]
