[package]
name = "sx1276"
version = "0.2.0"
authors = ["Nathan Corbyn <me@nathancorbyn.com>"]
edition = "2018"

[dependencies]
bit_field = "0.10.1"
crossbeam = "0.8.0"
rand = "0.8.1"

[dependencies.embedded-hal]
version = "0.2.2"
features = ["unproven"]
